#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Scitrera LLC
# SPDX-FileCopyrightText: 2026 Fox Engine Ltd.
# SPDX-License-Identifier: AGPL-3.0-only

"""Retain upstream notices for the executable and embedded UI on every release target.

Run after npm ci in web/. Go resolves the packages used by cmd/sparkroute with
CGO disabled on all six release targets. Test-only modules are not distributed.
Review upstream license changes whenever refreshing this generated bundle.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PLATFORMS = tuple(f"{system}/{arch}" for system in ("linux", "darwin", "windows") for arch in ("amd64", "arm64"))
NOTICE_PREFIXES = ("LICENSE", "LICENCE", "COPYING", "NOTICE", "PATENTS", "AUTHORS", "COPYRIGHT")
# These additional texts cover code incorporated into the linked packages.
EXTRA_NOTICES = {
    "github.com/grpc-ecosystem/grpc-gateway/v2": ["internal/casing/LICENSE.md"],
    "modernc.org/mathutil": ["mersenne/LICENSE", "mersenne/AUTHORS"],
}


def json_stream(value: str):
    decoder = json.JSONDecoder()
    while value.strip():
        value = value.lstrip()
        item, end = decoder.raw_decode(value)
        yield item
        value = value[end:]


def notice_paths(directory: Path) -> list[str]:
    return sorted(p.name for p in directory.iterdir() if p.is_file()
                  and p.name.upper().startswith(NOTICE_PREFIXES)
                  and p.name != "LICENSE-LOGO")  # The upstream logo is not shipped.


def collect(go: str, go_license_dir: Path | None = None) -> tuple[bytes, bytes]:
    def run(*args: str, env=None) -> str:
        return subprocess.check_output([go, *args], cwd=ROOT, env=env, text=True)

    modules = {}
    for platform in PLATFORMS:
        goos, goarch = platform.split("/")
        env = {**os.environ, "GOWORK": "off", "CGO_ENABLED": "0", "GOOS": goos, "GOARCH": goarch}
        for package in json_stream(run("list", "-mod=readonly", "-deps", "-json", "./cmd/sparkroute", env=env)):
            module = package.get("Module", {})
            if not module or module.get("Main"):
                continue
            if module.get("Replace"):
                raise ValueError("release notices require public modules without local replacements")
            modules[module["Path"]] = module

    components = [(name, m["Version"], Path(m["Dir"]),
                   notice_paths(Path(m["Dir"])) + EXTRA_NOTICES.get(name, []))
                  for name, m in sorted(modules.items())]
    go_version = run("env", "GOVERSION").strip()
    go_root = go_license_dir or Path(run("env", "GOROOT").strip())
    components.append(("Go", go_version, go_root, ["LICENSE", "PATENTS"]))

    lock = json.loads((ROOT / "web/package-lock.json").read_text())
    for name, package in sorted(lock["packages"].items()):
        if not name or package.get("dev") or package.get("devOptional"):
            continue
        directory = ROOT / "web" / name
        installed = json.loads((directory / "package.json").read_text())
        if installed["version"] != package["version"]:
            raise ValueError(f"stale npm installation for {name}; run npm ci")
        components.append(("npm:" + installed["name"], installed["version"], directory, notice_paths(directory)))

    sections = ["SparkRoute third-party license texts and notices\n"
                "Generated by scripts/collect-third-party-notices.py. Do not edit.\n"
                "Upstream text is retained verbatim below; component versions and\n"
                "file digests are recorded in third-party-manifest.json.\n"]
    manifest = {"schema_version": 1, "platforms": list(PLATFORMS), "components": []}
    for name, version, directory, paths in sorted(components):
        if not any(p.upper().startswith(("LICENSE", "LICENCE", "COPYING")) for p in paths):
            raise ValueError(f"no license text found for {name}")
        entry = {"name": name, "version": version, "notices": []}
        for relative in sorted(set(paths)):
            content = (directory / relative).read_bytes()
            entry["notices"].append({"path": relative, "sha256": hashlib.sha256(content).hexdigest()})
            sections.append(f"\n{'=' * 72}\n{name} {version} — {relative}\n{'=' * 72}\n\n" + content.decode("utf-8"))
        manifest["components"].append(entry)
    return ("\n".join(sections).encode(), (json.dumps(manifest, indent=2, sort_keys=True) + "\n").encode())


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--go", default="go")
    parser.add_argument("--go-license-dir", type=Path, help="Go LICENSE/PATENTS directory when using a container wrapper")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    bundle, manifest = collect(args.go, args.go_license_dir)
    for name, content in (("THIRD_PARTY_LICENSES.txt", bundle), ("third-party-manifest.json", manifest)):
        path = ROOT / name
        if args.check:
            if not path.exists() or path.read_bytes() != content:
                raise SystemExit(f"{name} is stale; regenerate third-party notices and rebuild web/")
        else:
            path.write_bytes(content)
        print(f"{'Checked' if args.check else 'Wrote'} {name}")


if __name__ == "__main__":
    main()
